# Generated by Django 3.0.6 on 2020-05-23 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '0001_initial'),
        ('editorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_pub', models.DateField(default=datetime.datetime(2020, 5, 23, 11, 20, 28, 184741, tzinfo=utc))),
                ('authors', models.ManyToManyField(to='autores.Author')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorials.Editorial')),
            ],
        ),
    ]
