# Generated by Django 3.0.6 on 2020-05-23 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_pub',
            field=models.DateField(default=datetime.datetime(2020, 5, 23, 11, 21, 47, 96332, tzinfo=utc), verbose_name='Fechas de publicacion'),
        ),
    ]
